version: '3.8'

services:
  # DATABASE MARIADB KHUSUS UNTUK APLIKASI
  donasi_db:
    image: mariadb:10.11
    container_name: donasi-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: donasi123
      MYSQL_DATABASE: donasi_db
    ports:
      - "3336:3336" # Buka port ini jika ingin melihat isinya lewat DBeaver/HeidiSQL dari laptop
    volumes:
      - db_data:/var/lib/mysql # Agar data tidak hilang saat server di-restart
      - ./init-db:/docker-entrypoint-initdb.d

  # API GATEWAY
  gateway:
    build: ./gateway
    container_name: donasi-gateway
    restart: always
    ports:
      - "3330:3330"
    environment:
      - PORT=3330
    depends_on:
      - auth
      - campaign
      - donation

  # 3. AUTH SERVICE
  auth:
    build: ./services/auth-service
    container_name: donasi-auth
    restart: always
    environment:
      - PORT=3331
      - DB_HOST=donasi_db
      - DB_USER=root
      - DB_PASSWORD=donasi123
      - DB_NAME=donasi_db
      - JWT_SECRET=donasi_secret
    depends_on:
      - donasi_db

  # CAMPAIGN SERVICE
  campaign:
    build: ./services/campaign-service
    container_name: donasi-campaign
    restart: always
    environment:
      - PORT=3332
      - DB_HOST=donasi_db
      - DB_USER=root
      - DB_PASSWORD=donasi123
      - DB_NAME=donasi_db
    depends_on:
      - donasi_db

  # DONATION SERVICE
  donation:
    build: ./services/donation-service
    container_name: donasi-donation
    restart: always
    environment:
      - PORT=3333
      - DB_HOST=donasi_db
      - DB_USER=root
      - DB_PASSWORD=donasi123
      - DB_NAME=donasi_db
    depends_on:
      - donasi_db

  # WORKER SERVICE
  worker:
    build: ./services/donation-service
    container_name: donasi-worker
    command: ["node", "worker.js"]
    restart: always
    environment:
      - DB_HOST=donasi_db

# Tempat penyimpanan data persisten untuk MariaDB
volumes:
  db_data: